[tool.black]
line-length = 99
target-version = ['py36']

[tool.ruff]
ignore = ["C901", "E501", "E741", "W605"]
select = ["C", "E", "F", "I", "W"]
line-length = 99

[tool.ruff.isort]
lines-after-imports = 2
known-first-party = ["neurocache"]

[isort]
default_section = "FIRSTPARTY"
known_first_party = "neurocache"
known_third_party = [
    "peft",
    "numpy",
    "torch",
    "accelerate",
    "transformers",
]
line_length = 99
lines_after_imports = 2
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.pytest]
doctest_optionflags = [
    "NORMALIZE_WHITESPACE",
    "ELLIPSIS",
    "NUMBER",
]
